POST http://localhost:8080/order
Content-Type: application/json

{
  "userId" : "john",
  "items" : [
    {"name": "Apple", "qtty":  10},
    {"name": "Pear", "qtty":  15}
  ]
}

###

POST http://localhost:8080/order/async
Content-Type: application/json

{
  "userId" : "john",
  "items" : [
    {"name": "Apple", "qtty":  10},
    {"name": "Pear", "qtty":  15}
  ]
}

###
